engineStrict: true
packages:
  - 'packages/*'
  - 'extensions/*'
  - 'extensions/*/packages/*'
  - 'storybook'
  - 'website'
  - 'website-argos'
  - 'tests/*'
  - 'scripts'

# https://pnpm.io/settings#minimumreleaseage
minimumReleaseAge: 1440

# https://pnpm.io/settings#overrides
overrides:
  extract-zip>yauzl: ^3.3.1
  '@xmldom/xmldom': ^0.8.12
  rollup: ^4.59.0
  react-router>path-to-regexp: ^1.9.0
  serve-handler>path-to-regexp: ^3.3.0
  express>cookie: ^0.7.0
  qs: ^6.15.2
  dompurify@^3: ^3.4.0
  webpack-dev-server>http-proxy-middleware: ^2.0.9
  esbuild-register>esbuild: ^0.25.0
  tsx>esbuild: ^0.25.0
  vite>esbuild: ^0.25.0
  node-forge: ^1.4.0
  config-file-ts>glob: ^10.5.0
  compression>on-headers: ^1.1.0
  electron-builder-notarize>js-yaml: ^3.14.2
  '@kubernetes/client-node>js-yaml': ^4.1.1
  tmp-promise>tmp: ^0.2.6
  tar: ^7.5.3
  cheerio>undici: ^7.18.2
  minimatch>@isaacs/brace-expansion: ^5.0.1
  brace-expansion@^1: ^1.1.14
  lodash-es: ^4.18.1
  lodash: ^4.18.1
  '@docusaurus/types>webpack': ^5.105.0
  minimatch@^3: ^3.1.5
  minimatch@^9: ^9.0.9
  minimatch@^10: ^10.2.4
  picomatch@^2: ^2.3.2
  picomatch@^3: ^3.0.2
  picomatch@^4: ^4.0.4
  serialize-javascript: ^7.0.5
  ajv@^6: ^6.14.0
  ajv@^8: ^8.18.0
  svelte>devalue: ^5.6.4
  protobufjs: ^7.5.6
  smol-toml: ^1.6.1
  follow-redirects: ^1.16.0
  uuid: ^14.0.0
  ip-address: '>=10.1.1'
  fast-uri: '>=3.1.1'
  '@babel/plugin-transform-modules-systemjs': '>=7.29.4'
  mermaid: '>=11.15.0'
  ws@^8: '>=8.20.1'
  concurrently>shell-quote: '>=1.8.4'

# https://pnpm.io/settings#nodelinker
nodeLinker: hoisted

# https://pnpm.io/settings#allowbuilds
allowBuilds:
  '@biomejs/biome': true
  core-js: true
  core-js-pure: true
  cpu-features: true
  electron: true
  electron-winstaller: false
  esbuild: true
  msw: true
  protobufjs: true
  sharp: true
  ssh2: true
  svelte-preprocess: true
  unrs-resolver: false
  win-ca: true
