export const mockReleaseData = {
  url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/224602012',
  assets_url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/224602012/assets',
  upload_url: 'https://uploads.github.com/repos/podman-desktop/podman-desktop/releases/224602012/assets{?name,label}',
  html_url: 'https://github.com/podman-desktop/podman-desktop/releases/tag/v1.19.2',
  id: 224602012,
  author: {
    login: 'github-actions[bot]',
    id: 41898282,
    node_id: 'MDM6Qm90NDE4OTgyODI=',
    avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/github-actions%5Bbot%5D',
    html_url: 'https://github.com/apps/github-actions',
    followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
    following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
    gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
    organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
    repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
    events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
    received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
    type: 'Bot',
    user_view_type: 'public',
    site_admin: false,
  },
  node_id: 'RE_kwDOG8Q6e84NYyec',
  tag_name: 'v1.19.2',
  target_commitish: 'main',
  name: 'v1.19.2',
  draft: false,
  immutable: false,
  prerelease: false,
  created_at: '2025-06-11T12:59:39Z',
  published_at: '2025-06-11T13:15:32Z',
  assets: [
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262944134',
      id: 262944134,
      node_id: 'RA_kwDOG8Q6e84PrDWG',
      name: 'latest-mac.yml',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'text/yaml',
      state: 'uploaded',
      size: 1172,
      digest: 'sha256:009a829f0d0ab21569fe7761b27b54e9d286d9fbdd9b5dbebd44a2b57189a31e',
      download_count: 1230015,
      created_at: '2025-06-11T13:12:58Z',
      updated_at: '2025-06-11T13:12:59Z',
      browser_download_url: 'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/latest-mac.yml',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262943098',
      id: 262943098,
      node_id: 'RA_kwDOG8Q6e84PrDF6',
      name: 'latest.yml',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'text/yaml',
      state: 'uploaded',
      size: 694,
      digest: 'sha256:f1869772bd143ad0295f03048e4d88b42b03a588457ccea36024a04473b3d94a',
      download_count: 1154760,
      created_at: '2025-06-11T13:08:07Z',
      updated_at: '2025-06-11T13:08:07Z',
      browser_download_url: 'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/latest.yml',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262942889',
      id: 262942889,
      node_id: 'RA_kwDOG8Q6e84PrDCp',
      name: 'podman-desktop-1.19.2-arm64.dmg',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 196649765,
      digest: 'sha256:7208c4c29124bd7ec97c153a9f6ad670ff2b09e72435a373d98d9c1bcd3b3f94',
      download_count: 18059,
      created_at: '2025-06-11T13:07:24Z',
      updated_at: '2025-06-11T13:07:30Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-1.19.2-arm64.dmg',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262942888',
      id: 262942888,
      node_id: 'RA_kwDOG8Q6e84PrDCo',
      name: 'podman-desktop-1.19.2-arm64.dmg.blockmap',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 206346,
      digest: 'sha256:1394f967c32455a7312d5f038c1da62a00f3d31bd4b23e4495482507bd785f35',
      download_count: 32,
      created_at: '2025-06-11T13:07:24Z',
      updated_at: '2025-06-11T13:07:24Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-1.19.2-arm64.dmg.blockmap',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262942884',
      id: 262942884,
      node_id: 'RA_kwDOG8Q6e84PrDCk',
      name: 'podman-desktop-1.19.2-arm64.exe',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 128626048,
      digest: 'sha256:1fec3cbc5a1a2ad23a38fb0972dda8f029cef3ecfbe8da167d24c142cd28fdc8',
      download_count: 224,
      created_at: '2025-06-11T13:07:24Z',
      updated_at: '2025-06-11T13:07:27Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-1.19.2-arm64.exe',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262943464',
      id: 262943464,
      node_id: 'RA_kwDOG8Q6e84PrDLo',
      name: 'podman-desktop-1.19.2-arm64.tar.gz',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/gzip',
      state: 'uploaded',
      size: 135877145,
      digest: 'sha256:34a228169616ac3b2641385c4fb92bffe9fa5cdab1f985a515a4cdba07bf70dd',
      download_count: 243,
      created_at: '2025-06-11T13:09:59Z',
      updated_at: '2025-06-11T13:10:02Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-1.19.2-arm64.tar.gz',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262943093',
      id: 262943093,
      node_id: 'RA_kwDOG8Q6e84PrDF1',
      name: 'podman-desktop-1.19.2-arm64.zip',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/zip',
      state: 'uploaded',
      size: 191137167,
      digest: 'sha256:a79ce8bc8d2a509d45b3f55472066b562ea79d58a49bdce1e0f05f216da41398',
      download_count: 30427,
      created_at: '2025-06-11T13:08:03Z',
      updated_at: '2025-06-11T13:08:10Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-1.19.2-arm64.zip',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262943094',
      id: 262943094,
      node_id: 'RA_kwDOG8Q6e84PrDF2',
      name: 'podman-desktop-1.19.2-arm64.zip.blockmap',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 201018,
      digest: 'sha256:a9399bbf7b3d3ce893b4a1ab239c5845185e659b6350b168462627e181fa0ab5',
      download_count: 22994,
      created_at: '2025-06-11T13:08:03Z',
      updated_at: '2025-06-11T13:08:03Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-1.19.2-arm64.zip.blockmap',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262943087',
      id: 262943087,
      node_id: 'RA_kwDOG8Q6e84PrDFv',
      name: 'podman-desktop-1.19.2-setup-arm64.exe',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 128807200,
      digest: 'sha256:c55a974ebdca38da227b1057a49dcaae5926ba9b9ccc10b50fbdfb40870d5f0f',
      download_count: 447,
      created_at: '2025-06-11T13:08:02Z',
      updated_at: '2025-06-11T13:08:07Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-1.19.2-setup-arm64.exe',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262943088',
      id: 262943088,
      node_id: 'RA_kwDOG8Q6e84PrDFw',
      name: 'podman-desktop-1.19.2-setup-arm64.exe.blockmap',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 134297,
      digest: 'sha256:ec3cf387f5e24938fa80e8afd4e8d8b2d7952e173e58686b01724a638206b97a',
      download_count: 30,
      created_at: '2025-06-11T13:08:02Z',
      updated_at: '2025-06-11T13:08:02Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-1.19.2-setup-arm64.exe.blockmap',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262943045',
      id: 262943045,
      node_id: 'RA_kwDOG8Q6e84PrDFF',
      name: 'podman-desktop-1.19.2-setup-x64.exe',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 126442616,
      digest: 'sha256:1c510ee0659b84d85d692d7c1cad6a68449c258a3df567eb21de0d3cbd61b582',
      download_count: 23487,
      created_at: '2025-06-11T13:07:50Z',
      updated_at: '2025-06-11T13:07:56Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-1.19.2-setup-x64.exe',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262943044',
      id: 262943044,
      node_id: 'RA_kwDOG8Q6e84PrDFE',
      name: 'podman-desktop-1.19.2-setup-x64.exe.blockmap',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 133676,
      digest: 'sha256:686f34d72b4bef1e197b7b14847285cc109c639c3120bf9ad19e394f61a7f1fa',
      download_count: 29,
      created_at: '2025-06-11T13:07:50Z',
      updated_at: '2025-06-11T13:07:51Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-1.19.2-setup-x64.exe.blockmap',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262942962',
      id: 262942962,
      node_id: 'RA_kwDOG8Q6e84PrDDy',
      name: 'podman-desktop-1.19.2-setup.exe',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 254688112,
      digest: 'sha256:f06aba9abdb4d3fd93701a2d4a9adfa7d40379537a4cd36db1dbfbefabf47111',
      download_count: 32903,
      created_at: '2025-06-11T13:07:38Z',
      updated_at: '2025-06-11T13:07:46Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-1.19.2-setup.exe',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262942961',
      id: 262942961,
      node_id: 'RA_kwDOG8Q6e84PrDDx',
      name: 'podman-desktop-1.19.2-setup.exe.blockmap',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 266114,
      digest: 'sha256:62965a965e4596ce910879ccc1f709401c7dd576eb6f95158d58fe7f39169810',
      download_count: 12249,
      created_at: '2025-06-11T13:07:38Z',
      updated_at: '2025-06-11T13:07:39Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-1.19.2-setup.exe.blockmap',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262943735',
      id: 262943735,
      node_id: 'RA_kwDOG8Q6e84PrDP3',
      name: 'podman-desktop-1.19.2-universal.dmg',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 314466805,
      digest: 'sha256:0d4751b61772849ffb7368a493d008af6d5730a36970db9e2506e23b9d77b95c',
      download_count: 19333,
      created_at: '2025-06-11T13:11:35Z',
      updated_at: '2025-06-11T13:11:48Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-1.19.2-universal.dmg',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262943736',
      id: 262943736,
      node_id: 'RA_kwDOG8Q6e84PrDP4',
      name: 'podman-desktop-1.19.2-universal.dmg.blockmap',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 330072,
      digest: 'sha256:aa9bf13009735ff406dbd543006c820fe8eeb994593c4ab579056d4f413eacdb',
      download_count: 26,
      created_at: '2025-06-11T13:11:35Z',
      updated_at: '2025-06-11T13:11:35Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-1.19.2-universal.dmg.blockmap',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262944093',
      id: 262944093,
      node_id: 'RA_kwDOG8Q6e84PrDVd',
      name: 'podman-desktop-1.19.2-universal.zip',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/zip',
      state: 'uploaded',
      size: 306196893,
      digest: 'sha256:50cbe03bec383e56855980757f167c456e741723ccf03b4d9661e255821bb798',
      download_count: 42,
      created_at: '2025-06-11T13:12:47Z',
      updated_at: '2025-06-11T13:12:58Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-1.19.2-universal.zip',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262944092',
      id: 262944092,
      node_id: 'RA_kwDOG8Q6e84PrDVc',
      name: 'podman-desktop-1.19.2-universal.zip.blockmap',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 321500,
      digest: 'sha256:381b3ca2627f029c7e62601a5c660ffbeaa376c7d548435c5d815842ab324698',
      download_count: 25,
      created_at: '2025-06-11T13:12:47Z',
      updated_at: '2025-06-11T13:12:47Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-1.19.2-universal.zip.blockmap',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262942279',
      id: 262942279,
      node_id: 'RA_kwDOG8Q6e84PrC5H',
      name: 'podman-desktop-1.19.2-x64.dmg',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 204735016,
      digest: 'sha256:3b6782a40a8dbbe724562814bde8347310e1340973b44fe3519bfd516116b732',
      download_count: 4999,
      created_at: '2025-06-11T13:04:27Z',
      updated_at: '2025-06-11T13:04:35Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-1.19.2-x64.dmg',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262942278',
      id: 262942278,
      node_id: 'RA_kwDOG8Q6e84PrC5G',
      name: 'podman-desktop-1.19.2-x64.dmg.blockmap',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 211711,
      digest: 'sha256:f5b8d57a7fe579917570af039551ccefbc771ca3c9daf6eb20b0bbb9282f2ff0',
      download_count: 25,
      created_at: '2025-06-11T13:04:27Z',
      updated_at: '2025-06-11T13:04:27Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-1.19.2-x64.dmg.blockmap',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262942872',
      id: 262942872,
      node_id: 'RA_kwDOG8Q6e84PrDCY',
      name: 'podman-desktop-1.19.2-x64.exe',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 126261160,
      digest: 'sha256:95db911ec66d9d53ea9ee869858eee2640ef713cfd57b8673777508aa7ff10af',
      download_count: 1121,
      created_at: '2025-06-11T13:07:18Z',
      updated_at: '2025-06-11T13:07:24Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-1.19.2-x64.exe',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262942421',
      id: 262942421,
      node_id: 'RA_kwDOG8Q6e84PrC7V',
      name: 'podman-desktop-1.19.2-x64.zip',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/zip',
      state: 'uploaded',
      size: 199256516,
      digest: 'sha256:d3aa0bdf9c1bd8a45fd3c3fbbf3df453d20e844f913b00d16fb7df18f8925c96',
      download_count: 3004,
      created_at: '2025-06-11T13:05:05Z',
      updated_at: '2025-06-11T13:05:16Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-1.19.2-x64.zip',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262942420',
      id: 262942420,
      node_id: 'RA_kwDOG8Q6e84PrC7U',
      name: 'podman-desktop-1.19.2-x64.zip.blockmap',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 210016,
      digest: 'sha256:d4022f9b6adc2416c171da1bf7c56915015419a30a6783854a08c7b9414bfbfd',
      download_count: 2122,
      created_at: '2025-06-11T13:05:05Z',
      updated_at: '2025-06-11T13:05:05Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-1.19.2-x64.zip.blockmap',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262942860',
      id: 262942860,
      node_id: 'RA_kwDOG8Q6e84PrDCM',
      name: 'podman-desktop-1.19.2.exe',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 254506912,
      digest: 'sha256:3c91b4936031b853c08e60583504d452eeb9147fe40e06445dbecfe560643117',
      download_count: 1216,
      created_at: '2025-06-11T13:07:14Z',
      updated_at: '2025-06-11T13:07:25Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-1.19.2.exe',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262943080',
      id: 262943080,
      node_id: 'RA_kwDOG8Q6e84PrDFo',
      name: 'podman-desktop-1.19.2.flatpak',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 98100240,
      digest: 'sha256:fe0ba89bf7aa3204417b4eee61fc4ddcddee9aa8793f7fa343eb0d4a627f2824',
      download_count: 3542,
      created_at: '2025-06-11T13:08:00Z',
      updated_at: '2025-06-11T13:08:03Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-1.19.2.flatpak',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262943276',
      id: 262943276,
      node_id: 'RA_kwDOG8Q6e84PrDIs',
      name: 'podman-desktop-1.19.2.tar.gz',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/gzip',
      state: 'uploaded',
      size: 135728127,
      digest: 'sha256:5ac55363a138e8b773f1cee1cd688970b321dc672a0381b3ce1e09428443e8df',
      download_count: 1612,
      created_at: '2025-06-11T13:09:03Z',
      updated_at: '2025-06-11T13:09:07Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-1.19.2.tar.gz',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262944041',
      id: 262944041,
      node_id: 'RA_kwDOG8Q6e84PrDUp',
      name: 'podman-desktop-airgap-1.19.2-arm64.dmg',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 1152804820,
      digest: 'sha256:7094d70e61c2289ae931ed64a38f3b7397e5823b3abc1f6320287eca8995da62',
      download_count: 229,
      created_at: '2025-06-11T13:12:38Z',
      updated_at: '2025-06-11T13:13:25Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-airgap-1.19.2-arm64.dmg',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262944042',
      id: 262944042,
      node_id: 'RA_kwDOG8Q6e84PrDUq',
      name: 'podman-desktop-airgap-1.19.2-arm64.dmg.blockmap',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 1196697,
      digest: 'sha256:728b61c803b468c8766bdef2dc5131217121c583114fd40042cc641cee12878a',
      download_count: 23,
      created_at: '2025-06-11T13:12:38Z',
      updated_at: '2025-06-11T13:12:38Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-airgap-1.19.2-arm64.dmg.blockmap',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262943150',
      id: 262943150,
      node_id: 'RA_kwDOG8Q6e84PrDGu',
      name: 'podman-desktop-airgap-1.19.2-arm64.exe',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 321874272,
      digest: 'sha256:4c096c6aad0cde4a09117de185cdb59de65b1025d87324209c275a3458219a2b',
      download_count: 27,
      created_at: '2025-06-11T13:08:21Z',
      updated_at: '2025-06-11T13:08:33Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-airgap-1.19.2-arm64.exe',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262944325',
      id: 262944325,
      node_id: 'RA_kwDOG8Q6e84PrDZF',
      name: 'podman-desktop-airgap-1.19.2-arm64.zip',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/zip',
      state: 'uploaded',
      size: 1146076438,
      digest: 'sha256:401fa643e5090b02182be02d064265f947d6dc9339a125aef820735bdc14582d',
      download_count: 28,
      created_at: '2025-06-11T13:14:06Z',
      updated_at: '2025-06-11T13:14:42Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-airgap-1.19.2-arm64.zip',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262944326',
      id: 262944326,
      node_id: 'RA_kwDOG8Q6e84PrDZG',
      name: 'podman-desktop-airgap-1.19.2-arm64.zip.blockmap',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 1190309,
      digest: 'sha256:f1ca84112ee85127984b16e0352f98b981d90a21c7d7ce7406575de203cfbb24',
      download_count: 26,
      created_at: '2025-06-11T13:14:06Z',
      updated_at: '2025-06-11T13:14:06Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-airgap-1.19.2-arm64.zip.blockmap',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262943320',
      id: 262943320,
      node_id: 'RA_kwDOG8Q6e84PrDJY',
      name: 'podman-desktop-airgap-1.19.2-setup-arm64.exe',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 322055424,
      digest: 'sha256:42028405ad16b1a6c654287d5a095c11e5cc71f8d20c3a06076bb5410ae55473',
      download_count: 64,
      created_at: '2025-06-11T13:09:13Z',
      updated_at: '2025-06-11T13:09:26Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-airgap-1.19.2-setup-arm64.exe',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262943321',
      id: 262943321,
      node_id: 'RA_kwDOG8Q6e84PrDJZ',
      name: 'podman-desktop-airgap-1.19.2-setup-arm64.exe.blockmap',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 335258,
      digest: 'sha256:5897be60caafd2d83dd7b3ff451ba48ba935c5b26751d86e454423bb96b92e27',
      download_count: 25,
      created_at: '2025-06-11T13:09:13Z',
      updated_at: '2025-06-11T13:09:13Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-airgap-1.19.2-setup-arm64.exe.blockmap',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262943266',
      id: 262943266,
      node_id: 'RA_kwDOG8Q6e84PrDIi',
      name: 'podman-desktop-airgap-1.19.2-setup-x64.exe',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 325567744,
      digest: 'sha256:78fd88fd32817ed109b7269694c5625e031be8a525b301130d651e0c62b33be6',
      download_count: 925,
      created_at: '2025-06-11T13:08:57Z',
      updated_at: '2025-06-11T13:09:06Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-airgap-1.19.2-setup-x64.exe',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262943267',
      id: 262943267,
      node_id: 'RA_kwDOG8Q6e84PrDIj',
      name: 'podman-desktop-airgap-1.19.2-setup-x64.exe.blockmap',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 341774,
      digest: 'sha256:a5405f3d169a8bd44a59c3727b61ce018e85b8eded8384e4787373ad4253b001',
      download_count: 30,
      created_at: '2025-06-11T13:08:57Z',
      updated_at: '2025-06-11T13:08:58Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-airgap-1.19.2-setup-x64.exe.blockmap',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262943212',
      id: 262943212,
      node_id: 'RA_kwDOG8Q6e84PrDHs',
      name: 'podman-desktop-airgap-1.19.2-setup.exe',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 647061464,
      digest: 'sha256:ad50ec2d3eb98f0d526eaf55c8b2983415d8955c1b0c58c9fc24d8a4c172937f',
      download_count: 31,
      created_at: '2025-06-11T13:08:42Z',
      updated_at: '2025-06-11T13:09:03Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-airgap-1.19.2-setup.exe',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262943213',
      id: 262943213,
      node_id: 'RA_kwDOG8Q6e84PrDHt',
      name: 'podman-desktop-airgap-1.19.2-setup.exe.blockmap',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 675255,
      digest: 'sha256:37899d6b0facbe090ce8585fcf8ff496e7e390e6bff5db2db610b967d6edd6f0',
      download_count: 25,
      created_at: '2025-06-11T13:08:43Z',
      updated_at: '2025-06-11T13:08:43Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-airgap-1.19.2-setup.exe.blockmap',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262943086',
      id: 262943086,
      node_id: 'RA_kwDOG8Q6e84PrDFu',
      name: 'podman-desktop-airgap-1.19.2-x64.dmg',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 1218526439,
      digest: 'sha256:1dd9a92238e8043952b66c0107070650bcd6ddd80a2afd72ac31d06056f8be31',
      download_count: 78,
      created_at: '2025-06-11T13:08:02Z',
      updated_at: '2025-06-11T13:08:55Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-airgap-1.19.2-x64.dmg',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262943085',
      id: 262943085,
      node_id: 'RA_kwDOG8Q6e84PrDFt',
      name: 'podman-desktop-airgap-1.19.2-x64.dmg.blockmap',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 1263127,
      digest: 'sha256:ac4e44286658013b2ebae6d71fb8df7334b965e2fc31cc0b320d0bfe0d32ec6b',
      download_count: 23,
      created_at: '2025-06-11T13:08:02Z',
      updated_at: '2025-06-11T13:08:02Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-airgap-1.19.2-x64.dmg.blockmap',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262943136',
      id: 262943136,
      node_id: 'RA_kwDOG8Q6e84PrDGg',
      name: 'podman-desktop-airgap-1.19.2-x64.exe',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 325386288,
      digest: 'sha256:b0605cbe137e678bec1522adea09d783d7aa8bb2414ee7accef7b3f7d5664a4b',
      download_count: 81,
      created_at: '2025-06-11T13:08:14Z',
      updated_at: '2025-06-11T13:08:26Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-airgap-1.19.2-x64.exe',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262943339',
      id: 262943339,
      node_id: 'RA_kwDOG8Q6e84PrDJr',
      name: 'podman-desktop-airgap-1.19.2-x64.zip',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/zip',
      state: 'uploaded',
      size: 1211626956,
      digest: 'sha256:405d5ae21d9f2b575a9fd628595ab387b0af01a964ab0b37002706eadecaa2a9',
      download_count: 43,
      created_at: '2025-06-11T13:09:23Z',
      updated_at: '2025-06-11T13:10:04Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-airgap-1.19.2-x64.zip',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262943341',
      id: 262943341,
      node_id: 'RA_kwDOG8Q6e84PrDJt',
      name: 'podman-desktop-airgap-1.19.2-x64.zip.blockmap',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 1264339,
      digest: 'sha256:45cbc978fc0be61aa9636aa10abb58b94067ae47ff2a34ce5d2f56263ffc79b4',
      download_count: 24,
      created_at: '2025-06-11T13:09:23Z',
      updated_at: '2025-06-11T13:09:25Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-airgap-1.19.2-x64.zip.blockmap',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262943100',
      id: 262943100,
      node_id: 'RA_kwDOG8Q6e84PrDF8',
      name: 'podman-desktop-airgap-1.19.2.exe',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'application/octet-stream',
      state: 'uploaded',
      size: 646880272,
      digest: 'sha256:e5c0bd013310e923080127d455a28757429e0836058b1256e960f8bf424c7853',
      download_count: 36,
      created_at: '2025-06-11T13:08:08Z',
      updated_at: '2025-06-11T13:08:31Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/podman-desktop-airgap-1.19.2.exe',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262945118',
      id: 262945118,
      node_id: 'RA_kwDOG8Q6e84PrDle',
      name: 'store-cache-pnpm-amd64.tgz',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'binary/octet-stream',
      state: 'uploaded',
      size: 421445393,
      digest: 'sha256:7c1915fb6028919b78c5f1db9d811692283f872c7bccac340bda985a0596b9bf',
      download_count: 18,
      created_at: '2025-06-11T13:17:25Z',
      updated_at: '2025-06-11T13:17:37Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/store-cache-pnpm-amd64.tgz',
    },
    {
      url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/assets/262945792',
      id: 262945792,
      node_id: 'RA_kwDOG8Q6e84PrDwA',
      name: 'store-cache-pnpm-arm64.tgz',
      label: '',
      uploader: {
        login: 'github-actions[bot]',
        id: 41898282,
        node_id: 'MDM6Qm90NDE4OTgyODI=',
        avatar_url: 'https://avatars.githubusercontent.com/in/15368?v=4',
        gravatar_id: '',
        url: 'https://api.github.com/users/github-actions%5Bbot%5D',
        html_url: 'https://github.com/apps/github-actions',
        followers_url: 'https://api.github.com/users/github-actions%5Bbot%5D/followers',
        following_url: 'https://api.github.com/users/github-actions%5Bbot%5D/following{/other_user}',
        gists_url: 'https://api.github.com/users/github-actions%5Bbot%5D/gists{/gist_id}',
        starred_url: 'https://api.github.com/users/github-actions%5Bbot%5D/starred{/owner}{/repo}',
        subscriptions_url: 'https://api.github.com/users/github-actions%5Bbot%5D/subscriptions',
        organizations_url: 'https://api.github.com/users/github-actions%5Bbot%5D/orgs',
        repos_url: 'https://api.github.com/users/github-actions%5Bbot%5D/repos',
        events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/events{/privacy}',
        received_events_url: 'https://api.github.com/users/github-actions%5Bbot%5D/received_events',
        type: 'Bot',
        user_view_type: 'public',
        site_admin: false,
      },
      content_type: 'binary/octet-stream',
      state: 'uploaded',
      size: 417784341,
      digest: 'sha256:834ede02a4684176f583d4ce3db6220007bb8e9251e3374323c978cd6efee172',
      download_count: 15,
      created_at: '2025-06-11T13:21:16Z',
      updated_at: '2025-06-11T13:21:27Z',
      browser_download_url:
        'https://github.com/podman-desktop/podman-desktop/releases/download/v1.19.2/store-cache-pnpm-arm64.tgz',
    },
  ],
  tarball_url: 'https://api.github.com/repos/podman-desktop/podman-desktop/tarball/v1.19.2',
  zipball_url: 'https://api.github.com/repos/podman-desktop/podman-desktop/zipball/v1.19.2',
  body: `## What's Changed\r\n* chore: update podman to v5.5.1 (backport #12762) by @mergify in https://github.com/podman-desktop/podman-desktop/pull/12804\r\n\r\n\r\n**Full Changelog**: https://github.com/podman-desktop/podman-desktop/compare/v1.19.1...v1.19.2`,
  reactions: {
    url: 'https://api.github.com/repos/podman-desktop/podman-desktop/releases/224602012/reactions',
    total_count: 6,
    '+1': 3,
    '-1': 0,
    laugh: 0,
    hooray: 0,
    confused: 0,
    heart: 2,
    rocket: 1,
    eyes: 0,
  },
  mentions_count: 1,
};
